In [4]:
#case 1:
import numpy as np

# Subway ridership for 5 stations on 10 different days
ridership = np.array([
    [   0,    0,    2,    5,    0],
    [1478, 3877, 3674, 2328, 2539],
    [1613, 4088, 3991, 6461, 2691],
    [1560, 3392, 3826, 4787, 2613],
    [1608, 4802, 3932, 4477, 2705],
    [1576, 3933, 3909, 4979, 2685],
    [  95,  229,  255,  496,  201],
    [   2,    0,    1,   27,    0],
    [1438, 3785, 3589, 4174, 2215],
    [1342, 4043, 4009, 4665, 3033]
])

# Change False to True for each block of code to see what it does

# Accessing elements
if 1:
    print(ridership[1, 3])
    print(ridership[1:3, 3:5])
    print(ridership[1, :])

2328
[[2328 2539]
 [6461 2691]]
[1478 3877 3674 2328 2539]


In [5]:
# Vectorized operations on rows or columns
if 1:
    print(ridership[0, :] + ridership[1, :])
    print(ridership[:, 0] + ridership[:, 1])

[1478 3877 3676 2333 2539]
[   0 5355 5701 4952 6410 5509  324    2 5223 5385]


In [3]:
# Vectorized operations on entire arrays
if 1:
    a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
    b = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])
    print(a + b)

[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]


In [11]:
print(ridership[0,:])
print(ridership[0,:].max())
print(ridership[0,:].argmax())
print(ridership.mean())

[0 0 2 5 0]
5
3
2342.6


In [15]:
#case study 2: 
'''
    Fill in this function to find the station with the maximum riders on the
    first day, then return the mean riders per day for that station. Also
    return the mean ridership overall for comparsion.'''
    
def mean_riders_for_max_station(ridership):
    '''
    Fill in this function to find the station with the maximum riders on the
    first day, then return the mean riders per day for that station. Also
    return the mean ridership overall for comparsion.
    
    Hint: NumPy's argmax() function might be useful:
    http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html
    '''
    #overall_mean = None # Replace this with your code
    #mean_for_max = None # Replace this with your code
    
    #station with max ridership on 1st day
    station_1_day_max=ridership[0,:].argmax()
    
    mean_for_max=ridership[:,station_1_day_max].mean()
    overall_mean=ridership.mean()
    
    
    return (overall_mean, mean_for_max)

print(mean_riders_for_max_station(ridership))

(2342.5999999999999, 3239.9000000000001)


In [16]:
#case study 2: operations along axis
'''
    Fill in this function. First, for each subway station, calculate the
    mean ridership per day. Then, out of all the subway stations, return the
    maximum and minimum of these values. That is, find the maximum
    mean-ridership-per-day and the minimum mean-ridership-per-day for any
    subway station.
'''
def min_and_max_riders_per_day(ridership):
    #mean ridership per day for each subway station
    ridership.mean(axis=0)
    
    
    max_daily_ridership = ridership.mean(axis=0).max()     # Replace this with your code
    min_daily_ridership = ridership.mean(axis=0).min()     # Replace this with your code
    
    #calculating mean ridership for each station
    
    
    return (max_daily_ridership, min_daily_ridership)


In [20]:
#pandas dataframe
import pandas as pd

# Subway ridership for 5 stations on 10 different days
ridership_df = pd.DataFrame(
    data=[[   0,    0,    2,    5,    0],
          [1478, 3877, 3674, 2328, 2539],
          [1613, 4088, 3991, 6461, 2691],
          [1560, 3392, 3826, 4787, 2613],
          [1608, 4802, 3932, 4477, 2705],
          [1576, 3933, 3909, 4979, 2685],
          [  95,  229,  255,  496,  201],
          [   2,    0,    1,   27,    0],
          [1438, 3785, 3589, 4174, 2215],
          [1342, 4043, 4009, 4665, 3033]],
    index=['05-01-11', '05-02-11', '05-03-11', '05-04-11', '05-05-11',
           '05-06-11', '05-07-11', '05-08-11', '05-09-11', '05-10-11'],
    columns=['R003', 'R004', 'R005', 'R006', 'R007']
)

ridership_df

R003  R004  R005  R006  R007
05-01-11     0     0     2     5     0
05-02-11  1478  3877  3674  2328  2539
05-03-11  1613  4088  3991  6461  2691
05-04-11  1560  3392  3826  4787  2613
05-05-11  1608  4802  3932  4477  2705
05-06-11  1576  3933  3909  4979  2685
05-07-11    95   229   255   496   201
05-08-11     2     0     1    27     0
05-09-11  1438  3785  3589  4174  2215
05-10-11  1342  4043  4009  4665  3033

In [39]:
#diff ways of accessing elements
# iloc() helps access by POSITION
print(ridership_df.iloc[0],"\n") # accessing elements of SINGLE ROW
print(ridership_df.iloc[1, 3],"\n") #accessing element at Single Posn

# loc() helps access by INDEX: 
print(ridership_df.loc['05-05-11'],"\n") #accessing elements of SINGLE ROW
print(ridership_df.loc['05-05-11','R003'],"\n") #accessing element at Single Posn


#accessing by column name
print(ridership_df['R003'],"\n") 


R003    0
R004    0
R005    2
R006    5
R007    0
Name: 05-01-11, dtype: int64 

2328 

R003    1608
R004    4802
R005    3932
R006    4477
R007    2705
Name: 05-05-11, dtype: int64 

1608 

05-01-11       0
05-02-11    1478
05-03-11    1613
05-04-11    1560
05-05-11    1608
05-06-11    1576
05-07-11      95
05-08-11       2
05-09-11    1438
05-10-11    1342
Name: R003, dtype: int64 



In [29]:
#accessing multiple rows
print(ridership_df.iloc[1:4,],"\n")

# Accessing multiple columns
print(ridership_df[['R003', 'R005']]) #notice the double brackets


          R003  R004  R005  R006  R007
05-02-11  1478  3877  3674  2328  2539
05-03-11  1613  4088  3991  6461  2691
05-04-11  1560  3392  3826  4787  2613 

          R003  R005
05-01-11     0     2
05-02-11  1478  3674
05-03-11  1613  3991
05-04-11  1560  3826
05-05-11  1608  3932
05-06-11  1576  3909
05-07-11    95   255
05-08-11     2     1
05-09-11  1438  3589
05-10-11  1342  4009


In [25]:
# You can create a DataFrame out of a dictionary mapping column names to values
df_1 = pd.DataFrame({'A': [0, 1, 2], #dictionary key-value pair
                     'B': [3, 4, 5]})
print(df_1,"\n")

df_2 = pd.DataFrame([[0, 1, 2], [3, 4, 5]], #2d array as rows
                    columns=['A', 'B', 'C'])
print(df_2)
   

   A  B
0  0  3
1  1  4
2  2  5 

   A  B  C
0  0  1  2
1  3  4  5


In [34]:
#pandas axis
df = pd.DataFrame({'A': [0, 1, 2], 'B': [3, 4, 5]})
print(df,"\n")
print(df.sum(),"\n") #by default sum is along columns
print(df.sum(axis=1),"\n") #find SUM across ROWS

#df.values gives output as numpy array, on which we can apply numpy functions to find sum of ALL values in dataframe
#values() gives only value of dataframe and not column name or index name
print("sum of all values in df= ", df.values.sum())


   A  B
0  0  3
1  1  4
2  2  5 

A     3
B    12
dtype: int64 

0    3
1    5
2    7
dtype: int64 

sum of all values in df  15


In [58]:
#case study
'''
    Fill in this function to find the station with the maximum riders on the
    first day, then return the mean riders per day for that station. Also
    return the mean ridership overall for comparsion.
    
    This is the same as a previous exercise, but this time the
    input is a Pandas DataFrame rather than a 2D NumPy array.
'''
    
def mean_riders_for_max_station(ridership_df):
        
    #station with ridership which is max on day 1
    station=ridership_df.iloc[0].argmax()
    mean_for_max = ridership_df.loc[:,station].mean() 
    
    #to calculate overall_mean: way 1
    x=ridership_df.iloc[:,:].mean() #this will give overall mean at column level
    overall_mean=x.mean() #now find mean of all columns
    
    #to calculate overall_mean: way 2: doing above in single line of code
    #overall_mean=ridership_df.loc[:,ridership_df.iloc[0].argmax()].mean()
    
    return (overall_mean, mean_for_max)

print(mean_riders_for_max_station(ridership_df))

(2342.6000000000004, 3239.9)


In [50]:
#print(ridership_df.iloc[0])
#print(ridership_df.iloc[0].argmax())
ridership_df.loc[:,ridership_df.iloc[0].argmax()].mean()
#ridership_df.iloc[0].argmax()

3239.9

In [59]:
#case study: writing our own pearson correlation r function
import pandas as pd

filename = '/datasets/ud170/subway/nyc_subway_weather.csv'
subway_df = pd.read_csv(filename)

def correlation(x, y):
    '''
    Fill in this function to compute the correlation between the two
    input variables. Each input is either a NumPy array or a Pandas
    Series.
    
    correlation = average of (x in standard units) times (y in standard units)
    
    Remember to pass the argument "ddof=0" to the Pandas std() function!
    '''
    #step1: standardize all values
    #note: ddof=0 means we are taking uncorrected standard variable. This is how pearson's r is caculated
    p=(x.values-x.values.mean())/x.values.std(ddof=0)
    q=(y.values-y.values.mean())/y.values.std(ddof=0)
    
    
    r=p*q
    
    #print p
    #print q
    #print r
    return r.mean()

entries = subway_df['ENTRIESn_hourly']
cum_entries = subway_df['ENTRIESn']
rain = subway_df['meanprecipi']
temp = subway_df['meantempi']

print correlation(entries, rain)
print correlation(entries, temp)
print correlation(rain, temp)


In [63]:
# Examples of vectorized operations on DataFrames:

# Adding DataFrames with the column names
df1 = pd.DataFrame({'a': [1, 2, 3], 'b': [4, 5, 6], 'c': [7, 8, 9]})
df2 = pd.DataFrame({'a': [10, 20, 30], 'b': [40, 50, 60], 'c': [70, 80, 90]})
print("Adding DataFrames with the column names\n",df1 + df2,"\n")
    
# Adding DataFrames with overlapping column names 
df1 = pd.DataFrame({'a': [1, 2, 3], 'b': [4, 5, 6], 'c': [7, 8, 9]})
df2 = pd.DataFrame({'d': [10, 20, 30], 'c': [40, 50, 60], 'b': [70, 80, 90]})
print("Adding DataFrames with overlapping column names\n",df1 + df2,"\n")

# Adding DataFrames with overlapping row indexes
df1 = pd.DataFrame({'a': [1, 2, 3], 'b': [4, 5, 6], 'c': [7, 8, 9]},
                   index=['row1', 'row2', 'row3'])
df2 = pd.DataFrame({'a': [10, 20, 30], 'b': [40, 50, 60], 'c': [70, 80, 90]},
                   index=['row4', 'row3', 'row2'])
print("Adding DataFrames with overlapping row indexes\n",df1 + df2,"\n")


Adding DataFrames with the column names
     a   b   c
0  11  44  77
1  22  55  88
2  33  66  99 

Adding DataFrames with overlapping column names
     a   b   c   d
0 NaN  74  47 NaN
1 NaN  85  58 NaN
2 NaN  96  69 NaN 

Adding DataFrames with overlapping row indexes
          a     b     c
row1   NaN   NaN   NaN
row2  32.0  65.0  98.0
row3  23.0  56.0  89.0
row4   NaN   NaN   NaN 



In [191]:
# --- Quiz ---
# Cumulative entries and exits for one station for a few hours.
entries_and_exits = pd.DataFrame({
    'ENTRIESn': [3144312, 3144335, 3144353, 3144424, 3144594,
                 3144808, 3144895, 3144905, 3144941, 3145094],
    'EXITSn': [1088151, 1088159, 1088177, 1088231, 1088275,
               1088317, 1088328, 1088331, 1088420, 1088753]
})

'''
Fill in this function to take a DataFrame with cumulative entries
and exits (entries in the first column, exits in the second) and
return a DataFrame with hourly entries and exits (entries in the
first column, exits in the second).
'''

def get_hourly_entries_and_exits(entries_and_exits):
    p=entries_and_exits.values
        
    from pandasql import sqldf
    col_series=pd.Series(entries_and_exits.columns)
    col_count=sqldf("select count(*) from col_series")

    num_cols=int(col_count.iloc[0])
    print("number of columns =",num_cols)

    for i in range(num_cols):
        print(entries_and_exits.columns[i],"=",i)

        entries_in_col=np.size(entries_and_exits.values[:,i])
        print("entries in columns =  ",entries_in_col)

        if i==0:
            new_array=np.zeros(shape=(num_cols,entries_in_col))
        my_array=entries_and_exits.values[:,i]
        #new_array=entries_and_exits.values[:,i]


        for j in range(entries_in_col):
            if j!=0:
                #print("hi")
                x=my_array[j]
                y=my_array[j-1]
                #new_array[j]=my_array[j]-my_array[j-1]
                new_array[i,j]=x-y
                x=my_array[j]
                y=my_array[j-1]
                #print(j," ",x," ",y,"",x-y,"\n")
                #print(my_array[j]," ",new_array[i,j],"\n")
            else:
                new_array[i,j]=0

            #print(my_array,"\n")
            #print(new_array)
    my_df=pd.DataFrame(new_array.transpose())
    #my_df.rename(columns={0:'ENTRIESn',1:'EXITSn'})   
    my_df.columns={'ENTRIESn','EXITSn'}
    return my_df

print(get_hourly_entries_and_exits(entries_and_exits))

number of columns = 2
ENTRIESn = 0
entries in columns =   10
EXITSn = 1
entries in columns =   10
   EXITSn  ENTRIESn
0     0.0       0.0
1    23.0       8.0
2    18.0      18.0
3    71.0      54.0
4   170.0      44.0
5   214.0      42.0
6    87.0      11.0
7    10.0       3.0
8    36.0      89.0
9   153.0     333.0


In [193]:
#alternate way to do above code is using shift() which moves values down by number specified in parameter to shift
def get_hourly_entries_and_exits_2(entries_and_exits):
    entries_and_exits2=entries_and_exits.shift(1)
    my_df=entries_and_exits-entries_and_exits2
    z=my_df.fillna(0) #drop missing values across axis=0 i.e. rows
    
    return z
print(get_hourly_entries_and_exits_2(entries_and_exits))

   ENTRIESn  EXITSn
0       0.0     0.0
1      23.0     8.0
2      18.0    18.0
3      71.0    54.0
4     170.0    44.0
5     214.0    42.0
6      87.0    11.0
7      10.0     3.0
8      36.0    89.0
9     153.0   333.0


In [113]:
from pandasql import sqldf
col_series=pd.Series(entries_and_exits.columns)
col_count=sqldf("select count(*) from col_series")
print(col_count.iloc[0])

count(*)    2
Name: 0, dtype: int64


In [90]:
x=np.size(entries_and_exits.values[:,0])

10

In [ ]:
p=entries_and_exits.values
from pandasql import sqldf
col_series=pd.Series(entries_and_exits.columns)
col_count=sqldf("select count(*) from col_series")

num_cols=int(col_count.iloc[0])
print("number of columns =",num_cols)

for i in range(num_cols):
    print(entries_and_exits.columns[i],"=",i)
    
    entries_in_col=np.size(entries_and_exits.values[:,i])
    print("entries in columns =  ",entries_in_col)
    
    if i==0:
        new_array=np.zeros(shape=(num_cols,entries_in_col))
    my_array=entries_and_exits.values[:,i]
    #new_array=entries_and_exits.values[:,i]
    
    
    for j in range(entries_in_col):
        if j!=0:
            #print("hi")
            x=my_array[j]
            y=my_array[j-1]
            #new_array[j]=my_array[j]-my_array[j-1]
            new_array[i,j]=x-y
        x=my_array[j]
        y=my_array[j-1]
        #print(j," ",x," ",y,"",x-y,"\n")
        #print(my_array[j]," ",new_array[i,j],"\n")
    
    
    #print(my_array,"\n")
    print(new_array)
    
    
        
    
    

   
    
    

#new case study: use of applymap()
#applymap() - for applying user defined function on each element of DATAFRAME


In [354]:
import pandas as pd

# DataFrame applymap()
if 0:
    df = pd.DataFrame({
        'a': [1, 2, 3],
        'b': [10, 20, 30],
        'c': [5, 10, 15]
    })
    
    def add_one(x):
        return x + 1
        
    print(df.applymap(add_one))
    
grades_df = pd.DataFrame(
    data={'exam1': [43, 81, 78, 75, 89, 70, 91, 65, 98, 87],
          'exam2': [24, 63, 56, 56, 67, 51, 79, 46, 72, 60]},
    index=['Andre', 'Barry', 'Chris', 'Dan', 'Emilio', 
           'Fred', 'Greta', 'Humbert', 'Ivan', 'James']
)

print(grades_df)


'''
Fill in this function to convert the given DataFrame of numerical
grades to letter grades. Return a new DataFrame with the converted
grade.

The conversion rule is:
    90-100 -> A
    80-89  -> B
    70-79  -> C
    60-69  -> D
    0-59   -> F
'''

def convert_grades(grades):
    row_count,col_count=np.shape(grades.values)
    my_df_array=grades.values
    #new_df=grades.copy() 
    new_df=grades
    for i in range(row_count):
        #print(i)
        for j in range(col_count):
            if 90<=my_df_array[i,j]<=100:
                new_df.iloc[i,j]='A'
            elif 80<=my_df_array[i,j]<=89:
                new_df.iloc[i,j]='B'
            elif 70<=my_df_array[i,j]<=79:
                new_df.iloc[i,j]='C'
            elif 60<=my_df_array[i,j]<=69:
                new_df.iloc[i,j]='D'
            else:
                new_df.iloc[i,j]='E'

    #print(new_df)  
    return new_df



#grades_df.applymap(convert_grades)
grades_df=convert_grades(grades_df)

grades_df


         exam1  exam2
Andre       43     24
Barry       81     63
Chris       78     56
Dan         75     56
Emilio      89     67
Fred        70     51
Greta       91     79
Humbert     65     46
Ivan        98     72
James       87     60


exam1 exam2
Andre       E     E
Barry       B     D
Chris       C     E
Dan         C     E
Emilio      B     D
Fred        C     E
Greta       A     C
Humbert     D     E
Ivan        A     C
James       B     D

In [250]:
grades_df = pd.DataFrame(
    data={'exam1': [43, 81, 78, 75, 89, 70, 91, 65, 98, 87],
          'exam2': [24, 63, 56, 56, 67, 51, 79, 46, 72, 60]},
    index=['Andre', 'Barry', 'Chris', 'Dan', 'Emilio', 
           'Fred', 'Greta', 'Humbert', 'Ivan', 'James']
)

print(grades_df)

#alternate way of doing above task: use applymap
#step 1: create function to apply on single grade

def convert_grade(grade):
    if grade>=90:
        return 'A'
    elif grade>=80:
        return 'B'
    elif grade>=70:
        return 'C'
    elif grade>=60:
        return 'D'
    else:
        return 'E'

#doing test run on single value
print(convert_grade(80))

#now applymap() is used to apply this function on each element of our dataframe
def convert_grades2(grades):
    return grades.applymap(convert_grade)

print(convert_grades2(grades_df))
    

         exam1  exam2
Andre       43     24
Barry       81     63
Chris       78     56
Dan         75     56
Emilio      89     67
Fred        70     51
Greta       91     79
Humbert     65     46
Ivan        98     72
James       87     60
B
        exam1 exam2
Andre       E     E
Barry       B     D
Chris       C     E
Dan         C     E
Emilio      B     D
Fred        C     E
Greta       A     C
Humbert     D     E
Ivan        A     C
James       B     D


In [251]:
grades_df = pd.DataFrame(
    data={'exam1': [43, 81, 78, 75, 89, 70, 91, 65, 98, 87],
          'exam2': [24, 63, 56, 56, 67, 51, 79, 46, 72, 60]},
    index=['Andre', 'Barry', 'Chris', 'Dan', 'Emilio', 
           'Fred', 'Greta', 'Humbert', 'Ivan', 'James']
)

print(grades_df)

#alternate way of doing above task: use applymap
#step 1: create function to apply on single grade

def convert_grade(grade):
    if grade>=90:
        return 'A'
    elif grade>=80:
        return 'B'
    elif grade>=70:
        return 'C'
    elif grade>=60:
        return 'D'
    else:
        return 'E'

#doing test run on single value
#print(convert_grade(80))

#now applymap() is used to apply this function on each element of our dataframe
def convert_grades2(grades):
    return grades.applymap(convert_grade)

print(convert_grades2(grades_df))

B
         exam1  exam2
Andre       43     24
Barry       81     63
Chris       78     56
Dan         75     56
Emilio      89     67
Fred        70     51
Greta       91     79
Humbert     65     46
Ivan        98     72
James       87     60
        exam1 exam2
Andre       E     E
Barry       B     D
Chris       C     E
Dan         C     E
Emilio      B     D
Fred        C     E
Greta       A     C
Humbert     D     E
Ivan        A     C
James       B     D


Apply() – can be applied on dataframe such that –
• It applies to each COLUMN, where each column is treated as individual series,  and returns a Series each time, so as to modify the DATAFRAME.
• It can also be applied to each COLUMN of a dataframe such that it for each column, it returns a single object, and final returned value is a SERIES


In [282]:
#case study: apply() function applies to each column of DATAFRAME. 
# In such case it treats each column as a Series.

import pandas as pd
import numpy as np
grades_df = pd.DataFrame(
    data={'exam1': [43, 81, 78, 75, 89, 70, 91, 65, 98, 87],
          'exam2': [24, 63, 56, 56, 67, 51, 79, 46, 72, 60]},
    index=['Andre', 'Barry', 'Chris', 'Dan', 'Emilio', 
           'Fred', 'Greta', 'Humbert', 'Ivan', 'James']
)

# Change False to True for this block of code to see what it does

# DataFrame apply() and qcut() function
def convert_grades_curve(exam_grades):
    # Pandas has a bult-in function that will perform this calculation
    # This will give the bottom 0% to 10% of students the grade 'F',
    # 10% to 20% the grade 'D', and so on. You can read more about
    # the qcut() function here:
    # http://pandas.pydata.org/pandas-docs/stable/generated/pandas.qcut.html
    return pd.qcut(exam_grades,
                   [0, 0.1, 0.2, 0.5, 0.8, 1],
                   labels=['F', 'D', 'C', 'B', 'A'])

# qcut() operates on a list, array, or Series. This is the
# result of running the function on a single column of the
# DataFrame.
print("apply() on 1 column of grades_df\n",convert_grades_curve(grades_df['exam1']))

# qcut() does not work on DataFrames, but we can use apply()
# to call the function on each column separately
print("apply() on all column of grades_df\n",grades_df.apply(convert_grades_curve))

#case study:
'''
    Fill in this function to standardize each column of the given
    DataFrame. To standardize a variable, convert each value to the
    number of standard deviations it is above or below the mean.
'''

def standardize(df):

    #print("\n",df.values.mean(axis=0))
    #print("\n",df.std(axis=0))
    return (df-df.mean())/df.std(ddof=0)

#pd.DataFrame(grades_df['exam1']).apply(standardize_1)
grades_df.apply(standardize)

#alternate way to do this
#step 1: function that works on single column
def standardize_col(my_column):
    return (my_column - my_column.mean())/my_column.std()

#step 2: apply on whole dataframe
def standardize_new(df):
    return df.apply(standardize_col)

standardize_new(grades_df)

apply() on 1 column of grades_df
 Andre      F
Barry      B
Chris      C
Dan        C
Emilio     B
Fred       C
Greta      A
Humbert    D
Ivan       A
James      B
Name: exam1, dtype: category
Categories (5, object): [F < D < C < B < A]
apply() on all column of grades_df
         exam1 exam2
Andre       F     F
Barry       B     B
Chris       C     C
Dan         C     C
Emilio      B     B
Fred        C     C
Greta       A     A
Humbert     D     D
Ivan        A     A
James       B     B


exam1     exam2
Andre   -2.196525 -2.186335
Barry    0.208891  0.366571
Chris    0.018990 -0.091643
Dan     -0.170911 -0.091643
Emilio   0.715295  0.628408
Fred    -0.487413 -0.418938
Greta    0.841896  1.413917
Humbert -0.803916 -0.746234
Ivan     1.284999  0.955703
James    0.588694  0.170194

In [285]:
# Here apply() used- 
'''It can also be applied to each COLUMN of a dataframe such that it for each column, 
it returns a single object, and final returned value is a SERIES'''

df = pd.DataFrame({
    'a': [4, 5, 3, 1, 2],
    'b': [20, 10, 40, 50, 30],
    'c': [25, 20, 5, 15, 10]
})

# Change False to True for this block of code to see what it does

# DataFrame apply() - use case 2
if 1: 
    print(df)
    print(df.apply(np.mean))
    print(df.apply(np.max))
    
'''
Fill in this function to return the second-largest value of each 
column of the input DataFrame.
'''
def second_largest(df):
    row_count,col_count=np.shape(df)
    print(type(df))
    my_arr=np.zeros(shape=(col_count))
    for i in range(col_count):
        max_val=df.iloc[:,i].max()
        max_val_posn=np.argmax(df.iloc[:,i])
        val=df.iloc[:,i].min()
        for j in range(row_count):
            if j!=max_val_posn:
                if val<df.iloc[j,i] :
                    val=df.iloc[j,i]
        
        my_arr[i]=val
        
        print(max_val," ",max_val_posn)
        print("2nd largest ",val)
           
    return pd.DataFrame(my_arr)

second_largest(df)

#alternate way to find 2nd largest value in DATAFRAME:
#step1: write function to find 2nd largest value in COLUMN
def second_largest_in_col(my_col):
    #first sort in DESCENDING order
    sorted_column=my_col.sort_values(ascending=False,inplace=False)
    #now largest value will be at posn o and 2nd largest value will be at posn 1
    return sorted_column.iloc[1]

#second_largest_in_col(df['a'])

#step2: apply this above function on whole dataframe
def second_largest_2(df):
    return df.apply(second_largest_in_col)

second_largest_2(df)

   a   b   c
0  4  20  25
1  5  10  20
2  3  40   5
3  1  50  15
4  2  30  10
a     3.0
b    30.0
c    15.0
dtype: float64
a     5
b    50
c    25
dtype: int64


# Adding DataFrame to Series : diff cases->
in adding a series to a dataframe-
This adds each value of Series to one column of the DataFrame
Matching in addition is done based on - index of Series with Col name of DataFrame

Case1: Adding a Series to a square DataFrame
Here addition is down row wise Vs col wise
df.col[i]+series.col[i]


In [344]:
s = pd.Series([1, 2, 3, 4])
df = pd.DataFrame({
    0: [10, 20, 30, 40],
    1: [50, 60, 70, 80],
    2: [90, 100, 110, 120],
    3: [130, 140, 150, 160]
})

print(df,"\n")
print(s,"\n")
print(df + s)

    0   1    2    3
0  10  50   90  130
1  20  60  100  140
2  30  70  110  150
3  40  80  120  160 

0    1
1    2
2    3
3    4
dtype: int64 

    0   1    2    3
0  11  52   93  134
1  21  62  103  144
2  31  72  113  154
3  41  82  123  164


case 2: Adding a Series to a one-row DataFrame 

In [345]:
s = pd.Series([1, 2, 3, 4])
df = pd.DataFrame({0: [10], 1: [20], 2: [30], 3: [40]})

print(df,"\n")
print(s,"\n")
print(df + s) 

    0   1   2   3
0  10  20  30  40 

0    1
1    2
2    3
3    4
dtype: int64 

    0   1   2   3
0  11  22  33  44


case3: Adding a Series to a one-column DataFrame

In [353]:
s = pd.Series([1, 2, 3, 4])
df = pd.DataFrame({0: [10, 20, 30, 40]})
    
print(df,"\n")
print(s,"\n")
print(df + s)
print(df.add(s,axis='columns')) #same as above
print(df.add(s,axis='index'))

    0
0  10
1  20
2  30
3  40 

0    1
1    2
2    3
3    4
dtype: int64 

    0   1   2   3
0  11 NaN NaN NaN
1  21 NaN NaN NaN
2  31 NaN NaN NaN
3  41 NaN NaN NaN
    0   1   2   3
0  11 NaN NaN NaN
1  21 NaN NaN NaN
2  31 NaN NaN NaN
3  41 NaN NaN NaN
    0
0  11
1  22
2  33
3  44


case 4: Adding when DataFrame column names match Series index

In [349]:
s = pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])
df = pd.DataFrame({
    'a': [10, 20, 30, 40],
    'b': [50, 60, 70, 80],
    'c': [90, 100, 110, 120],
    'd': [130, 140, 150, 160]
})
    
print(df,"\n")
print(s,"\n")
print(df + s)


    a   b    c    d
0  10  50   90  130
1  20  60  100  140
2  30  70  110  150
3  40  80  120  160 

a    1
b    2
c    3
d    4
dtype: int64 

    a   b    c    d
0  11  52   93  134
1  21  62  103  144
2  31  72  113  154
3  41  82  123  164


case 5: Adding when DataFrame column names don't match Series index

In [350]:
s = pd.Series([1, 2, 3, 4])
df = pd.DataFrame({
    'a': [10, 20, 30, 40],
    'b': [50, 60, 70, 80],
    'c': [90, 100, 110, 120],
    'd': [130, 140, 150, 160]
})
    
print(df,"\n")
print(s,"\n")
print(df + s)

    a   b    c    d
0  10  50   90  130
1  20  60  100  140
2  30  70  110  150
3  40  80  120  160 

0    1
1    2
2    3
3    4
dtype: int64 

    a   b   c   d   0   1   2   3
0 NaN NaN NaN NaN NaN NaN NaN NaN
1 NaN NaN NaN NaN NaN NaN NaN NaN
2 NaN NaN NaN NaN NaN NaN NaN NaN
3 NaN NaN NaN NaN NaN NaN NaN NaN


case study: standardize each col and each row w/o using apply function 

In [387]:
grades_df = pd.DataFrame(
    data={'exam1': [43, 81, 78, 75, 89, 70, 91, 65, 98, 87],
          'exam2': [24, 63, 56, 56, 67, 51, 79, 46, 72, 60]},
    index=['Andre', 'Barry', 'Chris', 'Dan', 'Emilio', 
           'Fred', 'Greta', 'Humbert', 'Ivan', 'James']
)

'''
    Fill in this function to standardize each column of the given
    DataFrame. To standardize a variable, convert each value to the
    number of standard deviations it is above or below the mean.

    This time, try to use vectorized operations instead of apply().
    You should get the same results as you did before.
'''

def std_cols(df):
    x=df.copy()
    #print(x)
    
    row_count,col_count=np.shape(x)
    print(row_count,col_count)
    
    for i in range(col_count):
        #print(x.iloc[:,i])
        
        col_mean=x.iloc[:,i].mean()
        col_std=x.iloc[:,i].std(ddof=0)
        #print("col_mean: ",col_mean) 
        #print("col_std: ",col_std)
        for j in range(row_count):
            t=x.iloc[j,i]
            x.iloc[j,i]=float((t-col_mean)/col_std)
               
    
    return x

print(std_cols(grades_df))

def std_cols2(df):
    x=df.copy()
    mean_col=x.mean()
    std_col=x.std(ddof=0)
    return ((x-mean_col)/std_col)

print(std_cols2(grades_df))


'''
    Fill in this function to standardize each row of the given
    DataFrame. Again, try not to use apply().

    This one is more challenging than standardizing each column!
'''

def std_rows(df):
    x=df.copy()
    #print(x)
    
    row_count,col_count=np.shape(x)
    print(row_count,col_count)
    for i in range(row_count):
        #print(x.iloc[:,i])
        
        col_mean=x.iloc[i,:].mean()
        col_std=x.iloc[i,:].std(ddof=0)
        #print("row_mean: ",col_mean) 
        #print("row_std: ",col_std)
        for j in range(col_count):
            t=x.iloc[i,j]
            #print(t)
            x.iloc[i,j]=float((t-col_mean)/col_std)
    return x
    #return None

print(std_rows(grades_df))


def std_rows2(df):
    x=df.copy()
    #to get mean of each row; axis=columns works on ROW, and returns a SERIES
    mean_row=x.mean(axis='columns')
    #to get std of each column; axis=columns works on ROW, and returns a SERIES
    std_row=x.std(axis='columns') 
    
    #to apply Series on columns of DataFrame
    #Step1:subtract series from dataframe using sub() function, and axis=index option
    mean_diff= x.sub(mean_row,axis='index')
    
    #Step2: Divide series from dataframe using div() function, and axis=index option
    y= mean_diff.div(std_row,axis='index')
    
    #print(mean_row, type(mean_row))
    #print(std_row, type(std_row))
    return y 
    
std_rows2(grades_df)


10 2
            exam1     exam2
Andre   -2.315341 -2.304599
Barry    0.220191  0.386400
Chris    0.020017 -0.096600
Dan     -0.180156 -0.096600
Emilio   0.753987  0.662400
Fred    -0.513779 -0.441600
Greta    0.887436  1.490400
Humbert -0.847401 -0.786600
Ivan     1.354508  1.007400
James    0.620538  0.179400
10 2
         exam1  exam2
Andre      1.0   -1.0
Barry      1.0   -1.0
Chris      1.0   -1.0
Dan        1.0   -1.0
Emilio     1.0   -1.0
Fred       1.0   -1.0
Greta      1.0   -1.0
Humbert    1.0   -1.0
Ivan       1.0   -1.0
James      1.0   -1.0


# Pandas Group BY

In [396]:
import numpy as np
import pandas as pd

values = np.array([1, 3, 2, 4, 1, 6, 4])
example_df = pd.DataFrame({
    'value': values,
    'even': values % 2 == 0,
    'above_three': values > 3 
}, index=['a', 'b', 'c', 'd', 'e', 'f', 'g'])

def standardize(xs):
    return (xs - xs.mean()) / xs.std()
grouped_data = example_df.groupby('even')
print(grouped_data['value'].apply(standardize))
    
# Find second largest value in each group
def second_largest(xs):
    sorted_xs = xs.sort(inplace=False, ascending=False)
    return sorted_xs.iloc[1]
grouped_data = example_df.groupby('even')
print(grouped_data['value'].apply(second_largest))


a   -0.577350
b    1.154701
c   -1.224745
d    0.000000
e   -0.577350
f    1.224745
g    0.000000
Name: value, dtype: float64
even
False    1
True     4
Name: value, dtype: int64


C:\Users\jai mata di\Anaconda3\lib\site-packages\ipykernel\__main__.py:18: FutureWarning: sort is deprecated, use sort_values(inplace=True) for INPLACE sorting


In [400]:
#Group BY Case Study:
# DataFrame with cumulative entries and exits for multiple stations
ridership_df = pd.DataFrame({
    'UNIT': ['R051', 'R079', 'R051', 'R079', 'R051', 'R079', 'R051', 'R079', 'R051'],
    'TIMEn': ['00:00:00', '02:00:00', '04:00:00', '06:00:00', '08:00:00', '10:00:00', '12:00:00', '14:00:00', '16:00:00'],
    'ENTRIESn': [3144312, 8936644, 3144335, 8936658, 3144353, 8936687, 3144424, 8936819, 3144594],
    'EXITSn': [1088151, 13755385,  1088159, 13755393,  1088177, 13755598, 1088231, 13756191,  1088275]
})

print(ridership_df)

def get_hourly_for_group(entries_and_exits):
    return (entries_and_exits-entries_and_exits.shift(1))


def get_hourly_entries_and_exits(entries_and_exits):
    '''
    Fill in this function to take a DataFrame with cumulative entries
    and exits and return a DataFrame with hourly entries and exits.
    The hourly entries and exits should be calculated separately for
    each station (the 'UNIT' column).
    
    Hint: Use the `get_hourly_entries_and_exits()` function you wrote
    in a previous quiz, DataFrame Vectorized Operations, and the `.apply()`
    function, to help solve this problem.
    '''
    x=entries_and_exits.groupby('UNIT')[['ENTRIESn','EXITSn']].apply(get_hourly_for_group).dropna()
    return x

print(get_hourly_entries_and_exits(ridership_df))


   ENTRIESn    EXITSn     TIMEn  UNIT
0   3144312   1088151  00:00:00  R051
1   8936644  13755385  02:00:00  R079
2   3144335   1088159  04:00:00  R051
3   8936658  13755393  06:00:00  R079
4   3144353   1088177  08:00:00  R051
5   8936687  13755598  10:00:00  R079
6   3144424   1088231  12:00:00  R051
7   8936819  13756191  14:00:00  R079
8   3144594   1088275  16:00:00  R051
    ENTRIESn      EXITSn     TIMEn  UNIT
0        NaN         NaN       NaN   NaN
1  3144312.0   1088151.0  00:00:00  R051
2  8936644.0  13755385.0  02:00:00  R079
3  3144335.0   1088159.0  04:00:00  R051
4  8936658.0  13755393.0  06:00:00  R079
5  3144353.0   1088177.0  08:00:00  R051
6  8936687.0  13755598.0  10:00:00  R079
7  3144424.0   1088231.0  12:00:00  R051
8  8936819.0  13756191.0  14:00:00  R079


   ENTRIESn  EXITSn
2      23.0     8.0
3      14.0     8.0
4      18.0    18.0
5      29.0   205.0
6      71.0    54.0
7     132.0   593.0
8     170.0    44.0
